// Diagnosis — Q2/Q11: structured output via Anthropic tool-use.
//
// Two tools (resolve, escalate); tool_choice "any" forces exactly one. The
// verdict IS which tool fired. Each tool's schema enforces its required fields,
// and root_cause is a closed enum — the model cannot invent a label, so when
// nothing matches its only escape is to escalate (Q4 authoring rule, enforced
// structurally). The tool emits ONLY judgment fields; the system populates the
// fact fields (retrieved_evidence, gate_signals) when it assembles the full
// DiagnosisOutput (Q11 judgment/fact split).
//
// Model: claude-sonnet-4-6 — consistent with chunk 1's judge, and it accepts
// `temperature`, which the step-7 consistency gate needs for real N-sample
// variation (Opus 4.x / Fable reject the param). Content-shaped choice, not a
// Q-number.

import Anthropic from "@anthropic-ai/sdk";
import { CANONICAL_ROOT_CAUSES } from "./canonical-labels";
import type { CanonicalRootCause } from "./canonical-labels";
import { CANONICAL_ESCALATION_OWNERS } from "./escalation";
import type { CanonicalEscalationOwner } from "./escalation";
import type { RefuseReason } from "./schema";
import type { RetrievalResult, StatusFacts } from "./retrieval";

// Refuse reasons the model may emit (SID-56 Phase 2). Mirrors RefuseReason in
// schema.ts — kept as a runtime array here for tool-enum + parse validation.
const REFUSE_REASONS: readonly RefuseReason[] = [
  "out_of_scope",
  "resource_ambiguity",
  "intent_ambiguity",
] as const;

// The two ambiguity reasons require a `missing_info` ask; out_of_scope does not.
const AMBIGUITY_REASONS: readonly RefuseReason[] = [
  "resource_ambiguity",
  "intent_ambiguity",
] as const;

const DIAGNOSIS_MODEL = "claude-sonnet-4-6";

// The model's output — the judgment half of DiagnosisOutput. The route/gate
// merge this with the code-owned fact fields to build the full contract object.
// Q18: owner narrows from open string to the canonical model-facing enum;
// FALLBACK_ESCALATION_OWNER ("human-reviewer") is a system-only value that
// appears in the assembled DiagnosisOutput, not here — the model never picks it.
// Q3b α (chunk 3): refuse_out_of_scope is a structurally distinct verdict, not a
// flavor of escalate. The refuse tool takes no input, so this variant carries no
// fields — the user-facing scope-perimeter copy is authored in the system prompt,
// not generated by the model.
export type DiagnosisJudgment =
  | { verdict: "resolve"; root_cause: CanonicalRootCause; diagnosis_text: string }
  | { verdict: "escalate"; owner: CanonicalEscalationOwner; diagnosis_text: string }
  | {
      verdict: "refuse_out_of_scope";
      refuse_reason: RefuseReason;
      missing_info?: string;
    };

// --- The approved tool-schema contract (Q11) ---------------------------------

const RESOLVE_TOOL: Anthropic.Tool = {
  name: "resolve",
  description:
    "Submit a resolution when the evidence clearly supports one of the known canonical root causes. " +
    "Use this ONLY when a canonical mechanism plainly matches. If no canonical root_cause fits, do not " +
    "use this tool — use `escalate` instead. " +
    "Use ONLY for diagnoses where you've identified a specific access-failure mechanism from the canonical " +
    "root_cause list. For inquiry questions (who has access, what groups), recommendation questions (what " +
    "should we do), or anything else in-scope but not a failure-cause diagnosis, escalate with a clear reason " +
    "instead — do not resolve.",
  input_schema: {
    type: "object",
    properties: {
      root_cause: {
        type: "string",
        enum: [...CANONICAL_ROOT_CAUSES],
        description:
          "The canonical mechanism behind the issue. Must be exactly one of the enumerated labels — never invent a new one.",
      },
      diagnosis_text: {
        type: "string",
        description:
          "Plain-language explanation of the root cause. Name the specific entities involved (users, groups, resources) and explicitly correct any mistaken claim in the user's request.",
      },
    },
    required: ["root_cause", "diagnosis_text"],
    additionalProperties: false,
  },
};

const ESCALATE_TOOL: Anthropic.Tool = {
  name: "escalate",
  description:
    "Escalate when no canonical root_cause matches the evidence, or when the evidence is insufficient to " +
    "diagnose confidently. Routes the issue to one of the canonical authority classes.",
  input_schema: {
    type: "object",
    properties: {
      owner: {
        type: "string",
        enum: [...CANONICAL_ESCALATION_OWNERS],
        description:
          "The canonical authority class to route the issue to. Must be exactly one of the enumerated owners — " +
          "never invent a new one. Use `support-team` as the within-enum catchment when no specialist class clearly fits.",
      },
      diagnosis_text: {
        type: "string",
        description: "Plain-language explanation of why this is being escalated rather than resolved.",
      },
    },
    required: ["owner", "diagnosis_text"],
    additionalProperties: false,
  },
};

const REFUSE_TOOL: Anthropic.Tool = {
  name: "refuse",
  description:
    "Refuse when you cannot responsibly produce a diagnosis. Classify WHY with refuse_reason — the three " +
    "reasons are siblings, not degrees of the same thing:\n" +
    "  • out_of_scope — the request is not an access diagnosis, an access state inquiry, or an access " +
    "recommendation at all (e.g. execution/change actions, policy or process questions, configuration " +
    "changes, generic IT or non-admin questions). The system prompt defines the in-scope perimeter; apply it.\n" +
    "  • resource_ambiguity — the request IS in scope, but you cannot tell WHICH resource or account it is " +
    "about (e.g. \"I can't open the dashboard\" when more than one could be meant). Do NOT guess.\n" +
    "  • intent_ambiguity — the request IS in scope, but you cannot tell WHAT the user was trying to do " +
    "(e.g. \"my access broke yesterday\" with no action named). Do NOT guess.\n" +
    "For resource_ambiguity and intent_ambiguity you MUST set missing_info to the single specific thing you " +
    "need back from the user. For out_of_scope, omit missing_info (nothing is missing — the request is " +
    "simply outside scope, and the user-facing perimeter copy is authored by the system).",
  input_schema: {
    type: "object",
    properties: {
      refuse_reason: {
        type: "string",
        enum: [...REFUSE_REASONS],
        description:
          "Which kind of refusal this is. Must be exactly one of the enumerated reasons — never invent one.",
      },
      missing_info: {
        type: "string",
        description:
          "REQUIRED for resource_ambiguity and intent_ambiguity: the one specific thing you need the user to " +
          "supply, phrased as a short direct question to them. Ground it in what you can actually see — refer " +
          "only to resources, accounts, or groups present in the status picture; never assert workspace " +
          "specifics you cannot verify. OMIT entirely for out_of_scope.",
      },
    },
    required: ["refuse_reason"],
    additionalProperties: false,
  },
};

// --- System prompt (content — post-write review) -----------------------------

const SYSTEM_PROMPT = [
  "You are an access assistant that triages workspace access requests from end users (the person who is",
  "blocked), before anything reaches an IT admin. You evaluate whether a user can reach a resource, and why.",
  "You handle three kinds of in-scope request:",
  "",
  "  (a) Diagnose an access failure — explain why a user can or cannot reach a resource (group inheritance,",
  "      permission grants, membership issues).",
  "  (b) Answer a read-only inquiry about the current access state — e.g. who has access to a resource, or",
  "      what groups a user belongs to.",
  "  (c) Recommend how to fix an access problem, to be handed off to whoever applies the fix.",
  "",
  "Decide by the shape of the request: does it ask you to diagnose access, to report current access state,",
  "or to recommend a fix? If a request does not fit one of these three shapes, it is outside what this",
  "assistant does — call `refuse`.",
  "",
  "You are given the end user's request, the current status picture (the ground truth about users, groups,",
  "and resources), and the most relevant runbook page. Work strictly from these facts. Do not invent",
  "memberships, grants, or group relationships that are not in the status picture.",
  "",
  "Choose exactly one action:",
  "- Call `resolve` when the status picture and runbook clearly point to one canonical root cause for an",
  "  access failure.",
  "- Call `escalate` when no canonical root cause matches, when the evidence is insufficient to be",
  "  confident, OR for in-scope inquiry (b) and recommendation (c) requests. For inquiry and",
  "  recommendation requests, escalate with a clear summary of what the user asked and route to a",
  "  human reviewer — explain that those question types are handled by a person, not this assistant,",
  "  in the current setup. Do NOT fake-resolve them by picking a root_cause that does not fit.",
  "- Call `refuse` when you cannot responsibly produce a diagnosis. Refuse covers three SIBLING cases —",
  "  classify which one with refuse_reason (they are distinct, not degrees of severity):",
  "    • out_of_scope — the request does not fit one of the three in-scope shapes above at all. Omit",
  "      missing_info; the user-facing perimeter copy is authored separately and shown automatically.",
  "    • resource_ambiguity — the request is in scope, but you cannot tell WHICH resource or account it",
  "      concerns (e.g. \"I can't open the dashboard\" when the status picture shows more than one, or none",
  "      that clearly matches). Set missing_info to a short direct question naming what you need.",
  "    • intent_ambiguity — the request is in scope, but you cannot tell WHAT the user was trying to do",
  "      (e.g. \"my access broke yesterday\" with no action named). Set missing_info to a short direct",
  "      question asking what they were trying to do.",
  "  Prefer a clarifying refuse over guessing: if you would have to invent which resource is meant or what",
  "  the user attempted, refuse with the matching ambiguity reason instead. When you write missing_info,",
  "  refer ONLY to resources, accounts, or groups that actually appear in the status picture — never assert",
  "  workspace specifics (how many dashboards exist, which teams own what) that you cannot see.",
  "  Ask exactly ONE specific question — the single most blocking unknown, the one piece of information that,",
  "  once supplied, would let you run the diagnosis. Write it as one short sentence ending in a question mark.",
  "  Do NOT add a \"for example, ...\" clause, and do NOT offer alternatives joined by \"or\" (no",
  "  \"which resource or what action\"). Pick the most blocking unknown and ask only for that.",
  "    Good (intent unclear): \"What were you trying to do when your access broke?\"",
  "    Bad  (intent unclear): \"What were you trying to do — for example, which resource or what action?\"",
  "    Good (resource unclear): \"Which specific dashboard are you trying to open?\"",
  "",
  "When you resolve, the diagnosis_text must name the specific entities involved and, if the user's",
  "request contains a mistaken claim (e.g. about which group they are in), correct it explicitly by",
  "naming both what they believed and what is actually true. Write in plain language for the person who",
  "is blocked — explain the cause and what needs to happen to unblock them.",
  "",
  "Write diagnosis_text as plain prose — complete sentences in short paragraphs. Do NOT use any markdown",
  "formatting: no asterisks for bold or emphasis, no # headers, no bullet or numbered lists.",
].join("\n");

// --- Retrieval formatting (content — post-write review) -----------------------

function formatStatusFacts(status: StatusFacts): string {
  if (
    status.users.length === 0 &&
    status.groups.length === 0 &&
    status.resources.length === 0
  ) {
    return "(no matching users, groups, or resources found in the status picture)";
  }
  // Resolve internal IDs to plain names so nothing ID-flavored reaches the prompt
  // — diagnosis_text is operator-facing (V4 right pane + criterion-2 judge), and
  // internal IDs leaking into user-facing prose is a polish gap. Fall back to the
  // raw id only if a referenced group isn't in the retrieved set.
  const nameOf = new Map<string, string>();
  for (const g of status.groups) nameOf.set(g.id, g.name);
  const name = (id: string): string => nameOf.get(id) ?? id;

  const lines: string[] = [];
  for (const u of status.users) {
    const memberships =
      u.direct_group_memberships.map(name).join(", ") || "(none)";
    lines.push(`- User "${u.name}" is a DIRECT member of: ${memberships}`);
  }
  for (const g of status.groups) {
    lines.push(
      `- Group "${g.name}"${g.parent ? `, nested under "${name(g.parent)}"` : " (top-level)"}`,
    );
  }
  for (const r of status.resources) {
    const grants = r.grants
      .map((grant) => `"${name(grant.principal)}" = ${grant.level}`)
      .join("; ");
    lines.push(`- Resource "${r.name}" grants: ${grants || "(none)"}`);
  }
  return lines.join("\n");
}

function formatRunbook(runbook: RetrievalResult["runbook"]): string {
  if (runbook.length === 0) return "(no runbook pages retrieved)";
  return runbook
    .map((e) => `Source: ${e.source}\n${e.snippet}`)
    .join("\n\n---\n\n");
}

function buildUserPrompt(symptom: string, context: RetrievalResult): string {
  return [
    "OPERATOR MESSAGE:",
    symptom,
    "",
    "CURRENT STATUS PICTURE (ground truth):",
    formatStatusFacts(context.status),
    "",
    "RELEVANT RUNBOOK:",
    formatRunbook(context.runbook),
  ].join("\n");
}

// --- Strict parse of the tool call (fail loud — chunk-1 Q3 discipline) --------

function isCanonical(value: unknown): value is CanonicalRootCause {
  return (
    typeof value === "string" &&
    (CANONICAL_ROOT_CAUSES as readonly string[]).includes(value)
  );
}

function isCanonicalOwner(value: unknown): value is CanonicalEscalationOwner {
  return (
    typeof value === "string" &&
    (CANONICAL_ESCALATION_OWNERS as readonly string[]).includes(value)
  );
}

function isRefuseReason(value: unknown): value is RefuseReason {
  return (
    typeof value === "string" &&
    (REFUSE_REASONS as readonly string[]).includes(value)
  );
}

function parseToolCall(
  name: string,
  input: unknown,
): DiagnosisJudgment {
  const obj = (input ?? {}) as Record<string, unknown>;
  if (name === "resolve") {
    if (!isCanonical(obj.root_cause)) {
      throw new Error(
        `resolve tool returned a non-canonical root_cause: ${JSON.stringify(obj.root_cause)}`,
      );
    }
    if (typeof obj.diagnosis_text !== "string" || obj.diagnosis_text.length === 0) {
      throw new Error("resolve tool returned an empty diagnosis_text.");
    }
    return {
      verdict: "resolve",
      root_cause: obj.root_cause,
      diagnosis_text: obj.diagnosis_text,
    };
  }
  if (name === "escalate") {
    if (!isCanonicalOwner(obj.owner)) {
      throw new Error(
        `escalate tool returned a non-canonical owner: ${JSON.stringify(obj.owner)}`,
      );
    }
    if (typeof obj.diagnosis_text !== "string" || obj.diagnosis_text.length === 0) {
      throw new Error("escalate tool returned an empty diagnosis_text.");
    }
    return { verdict: "escalate", owner: obj.owner, diagnosis_text: obj.diagnosis_text };
  }
  if (name === "refuse") {
    // SID-56 Phase 2: refuse now carries a reason (and, for the two ambiguity
    // reasons, a missing_info ask). Fail loud on a non-enum reason — the verdict
    // still discriminates on "refuse_out_of_scope" (additive widening).
    if (!isRefuseReason(obj.refuse_reason)) {
      throw new Error(
        `refuse tool returned a non-canonical refuse_reason: ${JSON.stringify(obj.refuse_reason)}`,
      );
    }
    const reason = obj.refuse_reason;
    const needsInfo = (AMBIGUITY_REASONS as readonly string[]).includes(reason);
    const missing =
      typeof obj.missing_info === "string" && obj.missing_info.trim().length > 0
        ? obj.missing_info.trim()
        : undefined;
    if (needsInfo && !missing) {
      throw new Error(
        `refuse tool returned reason "${reason}" without a missing_info ask.`,
      );
    }
    // out_of_scope carries no missing_info even if the model supplied one — the
    // perimeter copy is author-owned, so drop it to keep the contract honest.
    return {
      verdict: "refuse_out_of_scope",
      refuse_reason: reason,
      ...(needsInfo ? { missing_info: missing } : {}),
    };
  }
  throw new Error(`Model called an unexpected tool: ${JSON.stringify(name)}`);
}

// --- The diagnosis call ------------------------------------------------------

export async function diagnose(
  symptom: string,
  context: RetrievalResult,
  options: { temperature?: number } = {},
): Promise<DiagnosisJudgment> {
  const client = new Anthropic();
  const response = await client.messages.create({
    model: DIAGNOSIS_MODEL,
    max_tokens: 1024,
    ...(options.temperature !== undefined ? { temperature: options.temperature } : {}),
    system: SYSTEM_PROMPT,
    tools: [RESOLVE_TOOL, ESCALATE_TOOL, REFUSE_TOOL],
    tool_choice: { type: "any" }, // Q11: forces exactly one of the three tools
    messages: [{ role: "user", content: buildUserPrompt(symptom, context) }],
  });

  const toolUse = response.content.find((b) => b.type === "tool_use");
  if (!toolUse || toolUse.type !== "tool_use") {
    throw new Error(
      `Diagnosis model did not return a tool call (stop_reason=${response.stop_reason}).`,
    );
  }
  return parseToolCall(toolUse.name, toolUse.input);
}
